/**
 * Demo seed data — 60 hand-crafted hooks mapped to Monte's 6 patterns.
 * Used when Apify credentials are not configured so the app is always
 * demoable with real, relevant content.
 */

import type { PatternName } from './extractor';

export interface DemoHook {
  raw_text: string;
  hook_text: string;
  pattern_name: PatternName;
  source: 'linkedin' | 'reddit' | 'twitter';
  source_url: string;
  engagement_score: number;
  author_followers: number;
  reasoning: string;
}

export const DEMO_HOOKS: DemoHook[] = [
  // ---------------- The Rejection List ----------------
  {
    hook_text: 'I reviewed 17,000 resumes from Harvard, IIT, and Google.\nRejected 98% for these 5 reasons.',
    raw_text: 'I reviewed 17,000 resumes from Harvard, IIT, and Google. Rejected 98% for these 5 reasons. They listed skills, not outcomes. They used the word "synergy". They applied to 40 companies this week. They didn\'t know what we do. They asked about WFH before the interview. The 2% we kept? They sent work, not words.',
    pattern_name: 'The Rejection List',
    source: 'linkedin', source_url: 'https://linkedin.com/posts/demo-1',
    engagement_score: 12400, author_followers: 48000,
    reasoning: 'Authority + specific number + promise of concrete reasons.',
  },
  {
    hook_text: 'I audited 400 Amazon listings last month.\n91% were losing money for the same 3 reasons.',
    raw_text: 'I audited 400 Amazon listings last month. 91% were losing money for the same 3 reasons. Main image was a render, not a photo. Bullet 1 was a feature, not a benefit. They forgot mobile users read bullet 2 first. Fix the top of the page. The rest takes care of itself.',
    pattern_name: 'The Rejection List',
    source: 'linkedin', source_url: 'https://linkedin.com/posts/demo-2',
    engagement_score: 3200, author_followers: 14000,
    reasoning: 'Audit + rejection rate + fixable-cause promise.',
  },
  {
    hook_text: 'I read 220 cold emails to Pixii this week.\nDeleted 217 in under 4 seconds.',
    raw_text: 'I read 220 cold emails to Pixii this week. Deleted 217 in under 4 seconds. No subject line. Opened with "Hope you\'re well". Pitched me their agency, not a result. The 3 that worked attached before/after screenshots. Show the thing. Always.',
    pattern_name: 'The Rejection List',
    source: 'linkedin', source_url: 'https://linkedin.com/posts/demo-3',
    engagement_score: 5600, author_followers: 48000,
    reasoning: 'Time pressure + exact number rejected + fixable mistakes.',
  },
  {
    hook_text: 'I reviewed 1,200 pitch decks in 2024.\n94% got the opener wrong.',
    raw_text: 'I reviewed 1,200 pitch decks in 2024. 94% got the opener wrong. They led with the team. They led with the market size. They led with "we\'re like Uber for X". The 6% that got funded led with the insight nobody else had yet. Lead with the secret, not the resume.',
    pattern_name: 'The Rejection List',
    source: 'linkedin', source_url: 'https://linkedin.com/posts/demo-4',
    engagement_score: 8800, author_followers: 62000,
    reasoning: 'Year + review count + singular fixable mistake.',
  },
  {
    hook_text: 'I graded 300 AI portfolios this week.\nRejected 97% in under 10 seconds.',
    raw_text: 'I graded 300 AI portfolios this week. Rejected 97% in under 10 seconds. Every project was the same ChatGPT wrapper. Every readme used the word "revolutionary". Zero shipped to real users. Ship to strangers. Strangers are the only honest signal.',
    pattern_name: 'The Rejection List',
    source: 'linkedin', source_url: 'https://linkedin.com/posts/demo-5',
    engagement_score: 4100, author_followers: 22000,
    reasoning: 'Fast rejection speed + specific deal-breaker.',
  },
  {
    hook_text: 'We screened 2,800 agency portfolios for a client.\nFired 99% for the same single reason.',
    raw_text: 'We screened 2,800 agency portfolios for a client. Fired 99% for the same single reason. They showed logos, not lift. No conversion numbers. No CAC delta. No retention curve. Agencies that led with a revenue chart got the meeting. The rest got archived.',
    pattern_name: 'The Rejection List',
    source: 'linkedin', source_url: 'https://linkedin.com/posts/demo-6',
    engagement_score: 2900, author_followers: 18000,
    reasoning: 'Huge denominator + single-reason rejection feels decisive.',
  },
  {
    hook_text: 'I looked at 500 Shopify stores last weekend.\nMost were one image away from doubling sales.',
    raw_text: 'I looked at 500 Shopify stores last weekend. Most were one image away from doubling sales. Hero image was a stock photo. Product photo had 4 watermarks. Lifestyle shot was a render from 2019. The ones winning had a single photo that answered the buyer\'s first question. That\'s the whole job.',
    pattern_name: 'The Rejection List',
    source: 'reddit', source_url: 'https://reddit.com/r/ecommerce/demo-7',
    engagement_score: 3400, author_followers: 9000,
    reasoning: 'Concrete audit + single-change promise.',
  },
  {
    hook_text: 'Reviewed 90 seller applications for our accelerator.\nRejected 88 for pricing their product like a hobby.',
    raw_text: 'Reviewed 90 seller applications for our accelerator. Rejected 88 for pricing their product like a hobby. $12.99 margin on a $4 CAC. "I\'ll raise prices when I scale." You scale nothing if you ship at a loss. Fix unit economics first. Everything else is theater.',
    pattern_name: 'The Rejection List',
    source: 'linkedin', source_url: 'https://linkedin.com/posts/demo-8',
    engagement_score: 2100, author_followers: 11000,
    reasoning: 'Niche audit + punchy counter-frame.',
  },
  {
    hook_text: 'I interviewed 84 "AI engineers" this quarter.\n80 couldn\'t ship a working prompt.',
    raw_text: 'I interviewed 84 "AI engineers" this quarter. 80 couldn\'t ship a working prompt. They knew every paper. They couldn\'t debug a JSON schema. They talked RAG, never ran one. The 4 we hired had a public GitHub with ugly code that worked. Working > beautiful.',
    pattern_name: 'The Rejection List',
    source: 'linkedin', source_url: 'https://linkedin.com/posts/demo-9',
    engagement_score: 7700, author_followers: 48000,
    reasoning: 'Insider count + counterintuitive screen criteria.',
  },
  {
    hook_text: 'Went through 40 founder intros this week.\n37 pitched a product. 3 pitched a customer.',
    raw_text: 'Went through 40 founder intros this week. 37 pitched a product. 3 pitched a customer. The 3 had waitlists, screenshots, and a number. The 37 had decks and a Calendly link. If you lead with the customer, the product sells itself.',
    pattern_name: 'The Rejection List',
    source: 'linkedin', source_url: 'https://linkedin.com/posts/demo-10',
    engagement_score: 2600, author_followers: 21000,
    reasoning: 'Split-ratio framing makes the insight land.',
  },

  // ---------------- The Screenshot Reveal ----------------
  {
    hook_text: '646 minutes on this prompt.\n0 useful output.',
    raw_text: '646 minutes on this prompt. 0 useful output. To be fair, my prompt was: "Make me a billion dollars." Turns out the model is smarter than me.',
    pattern_name: 'The Screenshot Reveal',
    source: 'linkedin', source_url: 'https://linkedin.com/posts/demo-11',
    engagement_score: 9200, author_followers: 48000,
    reasoning: 'Absurd effort vs absurd output — self-deprecating.',
  },
  {
    hook_text: '$2,400 on Amazon photography.\n11% conversion rate.',
    raw_text: '$2,400 on Amazon photography. 11% conversion rate. Replaced them with Pixii renders. 19% conversion rate. $0 in photo costs. The studio lied. The pixels didn\'t.',
    pattern_name: 'The Screenshot Reveal',
    source: 'linkedin', source_url: 'https://linkedin.com/posts/demo-12',
    engagement_score: 5800, author_followers: 14000,
    reasoning: 'Before/after with dollar receipts.',
  },
  {
    hook_text: '48 hours in Cursor.\n0 lines of my own code.',
    raw_text: '48 hours in Cursor. 0 lines of my own code. Shipped a product. 312 paying users in week one. I\'m still not sure if I can code anymore. (I don\'t care.)',
    pattern_name: 'The Screenshot Reveal',
    source: 'twitter', source_url: 'https://twitter.com/demo-13',
    engagement_score: 14000, author_followers: 60000,
    reasoning: 'Shock number + punchline + parenthetical.',
  },
  {
    hook_text: '$89 in Claude API credits.\n$41,000 in closed revenue.',
    raw_text: '$89 in Claude API credits. $41,000 in closed revenue. The whole thing is a prompt, a cron, and a Google Sheet. Stop building platforms. Start building pipes.',
    pattern_name: 'The Screenshot Reveal',
    source: 'linkedin', source_url: 'https://linkedin.com/posts/demo-14',
    engagement_score: 6100, author_followers: 22000,
    reasoning: 'Tiny input vs huge output = jaw drop.',
  },
  {
    hook_text: '4 hours on the listing.\n0 sales that day.',
    raw_text: '4 hours on the listing. 0 sales that day. Changed the main image to a lifestyle render. 23 sales the next day. The image does the selling. The copy closes it.',
    pattern_name: 'The Screenshot Reveal',
    source: 'reddit', source_url: 'https://reddit.com/r/FulfillmentByAmazon/demo-15',
    engagement_score: 2400, author_followers: 4000,
    reasoning: 'Time-wasted → tiny-fix arc.',
  },
  {
    hook_text: '112 pages of user research.\n1 sentence that mattered.',
    raw_text: '112 pages of user research. 1 sentence that mattered. "I don\'t trust the photo." We rebuilt the whole product around that. Revenue doubled in 9 weeks.',
    pattern_name: 'The Screenshot Reveal',
    source: 'linkedin', source_url: 'https://linkedin.com/posts/demo-16',
    engagement_score: 7300, author_followers: 35000,
    reasoning: 'Big input vs one-line insight.',
  },
  {
    hook_text: '$0 ad spend this month.\n$180k in organic Amazon revenue.',
    raw_text: '$0 ad spend this month. $180k in organic Amazon revenue. Swapped every hero image. Rewrote every bullet 1. Cleaned the A+ content. Amazon\'s algorithm rewards listings that finish the sale.',
    pattern_name: 'The Screenshot Reveal',
    source: 'linkedin', source_url: 'https://linkedin.com/posts/demo-17',
    engagement_score: 9100, author_followers: 31000,
    reasoning: 'Zero-input + huge-output framing.',
  },
  {
    hook_text: '11 months building.\n2 weeks of traction.',
    raw_text: '11 months building. 2 weeks of traction. The only thing that changed was who we sold to. Same product. Different buyer. Sometimes PMF is just a list problem.',
    pattern_name: 'The Screenshot Reveal',
    source: 'twitter', source_url: 'https://twitter.com/demo-18',
    engagement_score: 6700, author_followers: 28000,
    reasoning: 'Long struggle → fast win reveal.',
  },
  {
    hook_text: '263 karma in 3 days.\n0 dollars spent on ads.',
    raw_text: '263 karma in 3 days. 0 dollars spent on ads. I answered 40 seller questions on r/FBA with actual screenshots. 14 DMs. 4 demos booked. Reddit is the most underpriced B2B channel of 2025.',
    pattern_name: 'The Screenshot Reveal',
    source: 'linkedin', source_url: 'https://linkedin.com/posts/demo-19',
    engagement_score: 4900, author_followers: 22000,
    reasoning: 'Small vanity metric → real pipeline.',
  },
  {
    hook_text: '1 prompt.\n4,200 listings rewritten overnight.',
    raw_text: '1 prompt. 4,200 listings rewritten overnight. Conversion up 14%. Returns down 8%. The bottleneck was never the writing. It was the courage to change everything at once.',
    pattern_name: 'The Screenshot Reveal',
    source: 'linkedin', source_url: 'https://linkedin.com/posts/demo-20',
    engagement_score: 8200, author_followers: 35000,
    reasoning: 'One-to-many scale reveal.',
  },

  // ---------------- The Contrarian Take ----------------
  {
    hook_text: '996 is weak.\nWhy not 12-12-7?',
    raw_text: '996 is weak. Why not 12-12-7? The people building the future aren\'t clocking out at 9pm. They\'re shipping at 2am because the problem is still open. The rest can optimize for balance. We\'re optimizing for the thing that matters.',
    pattern_name: 'The Contrarian Take',
    source: 'linkedin', source_url: 'https://linkedin.com/posts/demo-21',
    engagement_score: 21000, author_followers: 48000,
    reasoning: 'Punches up a sacred cow — pure engagement bait.',
  },
  {
    hook_text: 'Stop hiring senior engineers.\nHire unemployable ones.',
    raw_text: 'Stop hiring senior engineers. Hire unemployable ones. The best people I\'ve shipped with had gaps on their resume. They had side projects nobody asked for. They had opinions that got them fired. That energy built Pixii in 6 months.',
    pattern_name: 'The Contrarian Take',
    source: 'linkedin', source_url: 'https://linkedin.com/posts/demo-22',
    engagement_score: 11000, author_followers: 48000,
    reasoning: 'Direct counter + reframed archetype.',
  },
  {
    hook_text: 'Product photography is dead.\nAnd nobody told Amazon sellers yet.',
    raw_text: 'Product photography is dead. And nobody told Amazon sellers yet. A $2,000 studio day now costs $3 in compute. The only question is who moves first in your category. We\'re betting most sellers wait 18 months too long.',
    pattern_name: 'The Contrarian Take',
    source: 'linkedin', source_url: 'https://linkedin.com/posts/demo-23',
    engagement_score: 6400, author_followers: 31000,
    reasoning: 'Category-killer claim + urgency.',
  },
  {
    hook_text: 'MBAs are the new liberal arts degree.\nNobody needs one. Everyone has one.',
    raw_text: 'MBAs are the new liberal arts degree. Nobody needs one. Everyone has one. We hired 4 people without college degrees this quarter. They shipped more in week one than the MBAs did in a month. Credentials are a lagging indicator.',
    pattern_name: 'The Contrarian Take',
    source: 'linkedin', source_url: 'https://linkedin.com/posts/demo-24',
    engagement_score: 15000, author_followers: 48000,
    reasoning: 'Taboo comparison + evidence.',
  },
  {
    hook_text: 'Design doesn\'t matter at pre-seed.\nDistribution does.',
    raw_text: 'Design doesn\'t matter at pre-seed. Distribution does. I\'ve seen ugly products at $5M ARR. I\'ve seen gorgeous products at $0 ARR. Pick the boring fight. Win the channel first.',
    pattern_name: 'The Contrarian Take',
    source: 'twitter', source_url: 'https://twitter.com/demo-25',
    engagement_score: 8800, author_followers: 40000,
    reasoning: 'Heretical + evidence pairs.',
  },
  {
    hook_text: 'Work-life balance is a lagging indicator.\nOf work you don\'t love.',
    raw_text: 'Work-life balance is a lagging indicator. Of work you don\'t love. The founders I know who "balance" are the ones quietly quitting their own company. Build the thing you can\'t stop thinking about. Balance takes care of itself.',
    pattern_name: 'The Contrarian Take',
    source: 'linkedin', source_url: 'https://linkedin.com/posts/demo-26',
    engagement_score: 9800, author_followers: 48000,
    reasoning: 'Reframes a virtue as a symptom.',
  },
  {
    hook_text: 'Your North Star Metric is probably wrong.\nRevenue is the only one that doesn\'t lie.',
    raw_text: 'Your North Star Metric is probably wrong. Revenue is the only one that doesn\'t lie. DAU can be farmed. NPS can be coached. Activation can be redefined every quarter. Dollars collected cannot be spun.',
    pattern_name: 'The Contrarian Take',
    source: 'linkedin', source_url: 'https://linkedin.com/posts/demo-27',
    engagement_score: 5200, author_followers: 22000,
    reasoning: 'Attacks SaaS orthodoxy directly.',
  },
  {
    hook_text: '"Raise in 2 weeks" is the new 12-month round.\nIf you\'re not closed, you\'re not funded.',
    raw_text: '"Raise in 2 weeks" is the new 12-month round. If you\'re not closed, you\'re not funded. TS does not mean wire. Verbal does not mean signed. Assume zero until it hits the bank. That mindset has saved me twice this year.',
    pattern_name: 'The Contrarian Take',
    source: 'twitter', source_url: 'https://twitter.com/demo-28',
    engagement_score: 7100, author_followers: 40000,
    reasoning: 'Insider reality check.',
  },
  {
    hook_text: 'LinkedIn is not a job board.\nIt\'s a content-market-fit test.',
    raw_text: 'LinkedIn is not a job board. It\'s a content-market-fit test. If your post can\'t win a feed, your pitch can\'t win a meeting. Post daily. Let the algorithm grade your story before the customer does.',
    pattern_name: 'The Contrarian Take',
    source: 'linkedin', source_url: 'https://linkedin.com/posts/demo-29',
    engagement_score: 4600, author_followers: 19000,
    reasoning: 'Reframes a platform into a tool.',
  },
  {
    hook_text: 'Stop A/B testing your landing page.\nRewrite it.',
    raw_text: 'Stop A/B testing your landing page. Rewrite it. Moving a button 4 pixels won\'t save a bad headline. If the hero doesn\'t make someone stop, no optimization downstream matters. Fix the first sentence first.',
    pattern_name: 'The Contrarian Take',
    source: 'linkedin', source_url: 'https://linkedin.com/posts/demo-30',
    engagement_score: 6900, author_followers: 31000,
    reasoning: 'Kill-the-incremental-thinking take.',
  },

  // ---------------- The Personal Story Arc ----------------
  {
    hook_text: '50% of co-founders end in divorce.\nHere\'s how I picked mine. (we\'re scaling, it\'s working)',
    raw_text: '50% of co-founders end in divorce. Here\'s how I picked mine. (we\'re scaling, it\'s working) I watched him debug for 3 hours without complaining. He pushed back on my worst idea in week one. He cared more about the customer than the cap table. That\'s the whole framework.',
    pattern_name: 'The Personal Story Arc',
    source: 'linkedin', source_url: 'https://linkedin.com/posts/demo-31',
    engagement_score: 18000, author_followers: 48000,
    reasoning: 'Scary stat + vulnerable reveal + parenthetical brag.',
  },
  {
    hook_text: '80% of first-time founders fail.\nHere\'s what I did different the second time.',
    raw_text: '80% of first-time founders fail. Here\'s what I did different the second time. I sold before I built. I hired slow, fired fast. I stopped defending bad ideas in meetings. Pixii is 6 months old. It\'s already past what my first company did in 3 years.',
    pattern_name: 'The Personal Story Arc',
    source: 'linkedin', source_url: 'https://linkedin.com/posts/demo-32',
    engagement_score: 9400, author_followers: 48000,
    reasoning: 'Stat + earned lesson list.',
  },
  {
    hook_text: '70% of my seed-round intros ghosted.\nHere\'s how I got a term sheet anyway.',
    raw_text: '70% of my seed-round intros ghosted. Here\'s how I got a term sheet anyway. I stopped asking for money. I started sharing the weekly metrics email with 40 investors. By month 3 they were asking me to take the meeting.',
    pattern_name: 'The Personal Story Arc',
    source: 'linkedin', source_url: 'https://linkedin.com/posts/demo-33',
    engagement_score: 6100, author_followers: 22000,
    reasoning: 'Pain stat + counterintuitive play.',
  },
  {
    hook_text: '90% of my first hires quit in under a year.\nHere\'s what I changed.',
    raw_text: '90% of my first hires quit in under a year. Here\'s what I changed. Wrote a one-page "what we\'re building" memo. Made every interview end with a paid trial day. Fired on culture, not output. Current team retention: 100% over 14 months.',
    pattern_name: 'The Personal Story Arc',
    source: 'linkedin', source_url: 'https://linkedin.com/posts/demo-34',
    engagement_score: 7800, author_followers: 35000,
    reasoning: 'Failure confession + fix list.',
  },
  {
    hook_text: '38% of my burn went to photography last year.\nHere\'s what I replaced it with.',
    raw_text: '38% of my burn went to photography last year. Here\'s what I replaced it with. One render pipeline. One stylist review. One Amazon-ready export. Burn on creative: down 94%. Listings shipped: up 6x. (still wild to me)',
    pattern_name: 'The Personal Story Arc',
    source: 'linkedin', source_url: 'https://linkedin.com/posts/demo-35',
    engagement_score: 4400, author_followers: 14000,
    reasoning: 'Ownership of waste + fix.',
  },
  {
    hook_text: '65% of founders hide their numbers.\nI publish mine every Friday.',
    raw_text: '65% of founders hide their numbers. I publish mine every Friday. MRR, churn, runway, hires, misses. It terrified me for the first 4 weeks. It\'s now our best recruiting tool. Radical transparency is a moat.',
    pattern_name: 'The Personal Story Arc',
    source: 'twitter', source_url: 'https://twitter.com/demo-36',
    engagement_score: 11000, author_followers: 40000,
    reasoning: 'Stat + contrarian personal choice.',
  },
  {
    hook_text: '2 in 3 startups die from the wrong first hire.\nMine almost did.',
    raw_text: '2 in 3 startups die from the wrong first hire. Mine almost did. I hired a "VP" at month 4. He had 15 years of experience. He had 0 energy for the messy part. I let him go in 9 weeks. Never hire a title again.',
    pattern_name: 'The Personal Story Arc',
    source: 'linkedin', source_url: 'https://linkedin.com/posts/demo-37',
    engagement_score: 8600, author_followers: 48000,
    reasoning: 'Fear stat + personal scar + rule.',
  },
  {
    hook_text: 'I spent 3 years at a F500 before quitting.\nHere\'s what I learned the day after I left.',
    raw_text: 'I spent 3 years at a F500 before quitting. Here\'s what I learned the day after I left. The calendar wasn\'t work. The deck wasn\'t work. Work is the thing the customer pays for. Everything else is performance.',
    pattern_name: 'The Personal Story Arc',
    source: 'linkedin', source_url: 'https://linkedin.com/posts/demo-38',
    engagement_score: 5700, author_followers: 22000,
    reasoning: 'Origin + earned reframe.',
  },
  {
    hook_text: '1 in 4 founders burn out before Series A.\nI did too. Here\'s what worked.',
    raw_text: '1 in 4 founders burn out before Series A. I did too. Here\'s what worked. Phone off from 10pm. One full day a week with no calendar. One friend who had nothing to do with startups. Output went up. Therapy bills went down.',
    pattern_name: 'The Personal Story Arc',
    source: 'linkedin', source_url: 'https://linkedin.com/posts/demo-39',
    engagement_score: 9900, author_followers: 48000,
    reasoning: 'Vulnerability + specific protocol.',
  },
  {
    hook_text: '95% of my cold DMs get ignored.\nThe 5% built Pixii.',
    raw_text: '95% of my cold DMs get ignored. The 5% built Pixii. First customer: cold DM. First hire: cold DM. First investor: cold DM. The hit rate doesn\'t matter. The hit does.',
    pattern_name: 'The Personal Story Arc',
    source: 'linkedin', source_url: 'https://linkedin.com/posts/demo-40',
    engagement_score: 6800, author_followers: 48000,
    reasoning: 'Rejection rate + consequential outcome.',
  },

  // ---------------- The Data Drop ----------------
  {
    hook_text: 'We got 3,000 job applications in 6 days.\n5 people stood out BEFORE we started resume review.',
    raw_text: 'We got 3,000 job applications in 6 days. 5 people stood out BEFORE we started resume review. They found a way to get in touch with us, and sent us something cool. One sent a Loom. One rebuilt our landing page. One pitched us on a role we hadn\'t posted yet. The other 2,995 are just files in a queue.',
    pattern_name: 'The Data Drop',
    source: 'linkedin', source_url: 'https://linkedin.com/posts/demo-41',
    engagement_score: 25000, author_followers: 48000,
    reasoning: 'Raw number + tiny signal fraction.',
  },
  {
    hook_text: 'We shipped 14 features in 8 weeks.\n2 drove 97% of the revenue.',
    raw_text: 'We shipped 14 features in 8 weeks. 2 drove 97% of the revenue. Bulk listing export. 1-click image regeneration. The other 12 made the roadmap look busy. Kill the busy. Double the winners.',
    pattern_name: 'The Data Drop',
    source: 'linkedin', source_url: 'https://linkedin.com/posts/demo-42',
    engagement_score: 7200, author_followers: 31000,
    reasoning: 'Pareto reveal with specifics.',
  },
  {
    hook_text: 'We got 412 demo requests last month.\n389 came from one LinkedIn post.',
    raw_text: 'We got 412 demo requests last month. 389 came from one LinkedIn post. It had no image. 6 lines of copy. One specific number in the hook. Distribution compounds. Write the post.',
    pattern_name: 'The Data Drop',
    source: 'linkedin', source_url: 'https://linkedin.com/posts/demo-43',
    engagement_score: 8800, author_followers: 22000,
    reasoning: 'Total + one-source dominance.',
  },
  {
    hook_text: 'We onboarded 210 Amazon sellers in Q3.\n190 came from seller Slack groups.',
    raw_text: 'We onboarded 210 Amazon sellers in Q3. 190 came from seller Slack groups. We didn\'t spam. We answered questions for 8 weeks. No pitch. Just help. Trust is the only scalable CAC.',
    pattern_name: 'The Data Drop',
    source: 'linkedin', source_url: 'https://linkedin.com/posts/demo-44',
    engagement_score: 5600, author_followers: 14000,
    reasoning: 'Channel concentration + tactic.',
  },
  {
    hook_text: 'We wrote 120 cold emails this week.\n22 replied. 8 booked. 3 paid.',
    raw_text: 'We wrote 120 cold emails this week. 22 replied. 8 booked. 3 paid. Every email referenced a specific listing on their store. Every P.S. had a Loom. Pipeline is still a numbers game. The numbers are just more honest than people admit.',
    pattern_name: 'The Data Drop',
    source: 'linkedin', source_url: 'https://linkedin.com/posts/demo-45',
    engagement_score: 4300, author_followers: 22000,
    reasoning: 'Funnel numbers end-to-end.',
  },
  {
    hook_text: 'We ran 6 paid ad experiments.\n5 flopped. 1 paid for the year.',
    raw_text: 'We ran 6 paid ad experiments. 5 flopped. 1 paid for the year. The winner wasn\'t the best creative. It was the landing page that matched the ad promise word-for-word. Message match is the whole game.',
    pattern_name: 'The Data Drop',
    source: 'linkedin', source_url: 'https://linkedin.com/posts/demo-46',
    engagement_score: 6500, author_followers: 22000,
    reasoning: 'Hit ratio with strategic lesson.',
  },
  {
    hook_text: 'We interviewed 60 customers in 30 days.\n12 said the same 4 words.',
    raw_text: 'We interviewed 60 customers in 30 days. 12 said the same 4 words. "It\'s the photo, not the copy." We rebuilt the whole funnel around that sentence. Conversion doubled in 5 weeks.',
    pattern_name: 'The Data Drop',
    source: 'linkedin', source_url: 'https://linkedin.com/posts/demo-47',
    engagement_score: 9100, author_followers: 35000,
    reasoning: 'Sample size + verbatim insight.',
  },
  {
    hook_text: 'We shipped 38 blog posts.\n1 brought 84% of organic traffic.',
    raw_text: 'We shipped 38 blog posts. 1 brought 84% of organic traffic. It was a 6-hour teardown of a competitor\'s worst listing. Specific beats clever. Every time.',
    pattern_name: 'The Data Drop',
    source: 'linkedin', source_url: 'https://linkedin.com/posts/demo-48',
    engagement_score: 5200, author_followers: 19000,
    reasoning: 'Power-law content reveal.',
  },
  {
    hook_text: 'We tested 22 headlines on the homepage.\n1 lifted signups 41%.',
    raw_text: 'We tested 22 headlines on the homepage. 1 lifted signups 41%. "Amazon listings that sell themselves." The other 21 were clever. This one was a promise.',
    pattern_name: 'The Data Drop',
    source: 'linkedin', source_url: 'https://linkedin.com/posts/demo-49',
    engagement_score: 7600, author_followers: 31000,
    reasoning: 'Variant count + lift number + winning line.',
  },
  {
    hook_text: 'We ran 400 product images through Pixii last week.\n12 went viral. 0 came from a studio.',
    raw_text: 'We ran 400 product images through Pixii last week. 12 went viral. 0 came from a studio. The hero shot is the ad, the landing page, and the listing. Compute beats tripods now.',
    pattern_name: 'The Data Drop',
    source: 'linkedin', source_url: 'https://linkedin.com/posts/demo-50',
    engagement_score: 8100, author_followers: 31000,
    reasoning: 'Volume + zero-baseline reveal.',
  },

  // ---------------- The Bold Claim + Evidence ----------------
  {
    hook_text: 'Product photographers are about to lose their jobs.\nHere\'s what\'s coming.',
    raw_text: 'Product photographers are about to lose their jobs. Here\'s what\'s coming. - A studio day cost $2,400 in 2022. It costs $3 in 2025. - Amazon rewards listings that update weekly. No studio can keep up. - Every major brand I know is testing AI renders this quarter. The only question is who shuts the studio first.',
    pattern_name: 'The Bold Claim + Evidence',
    source: 'linkedin', source_url: 'https://linkedin.com/posts/demo-51',
    engagement_score: 14000, author_followers: 48000,
    reasoning: 'Job-loss prediction + three hard data points.',
  },
  {
    hook_text: 'Most seed-stage "AI" startups die in 2025.\nThree reasons why.',
    raw_text: 'Most seed-stage "AI" startups die in 2025. Three reasons why. - They built on a model that got commoditized. - They sold to buyers who don\'t renew. - They raised too much and shipped too little. The survivors will own a workflow, not a wrapper.',
    pattern_name: 'The Bold Claim + Evidence',
    source: 'linkedin', source_url: 'https://linkedin.com/posts/demo-52',
    engagement_score: 9700, author_followers: 48000,
    reasoning: 'Prediction + causal list.',
  },
  {
    hook_text: 'The best Amazon listings of 2025 will have zero photography.\nI\'ll prove it.',
    raw_text: 'The best Amazon listings of 2025 will have zero photography. I\'ll prove it. - A brand we work with cut their shoot budget to $0. - Their conversion rate is up 22%. - Their cost per listing image went from $80 to $0.04. The future is compute, not commutes to a studio.',
    pattern_name: 'The Bold Claim + Evidence',
    source: 'linkedin', source_url: 'https://linkedin.com/posts/demo-53',
    engagement_score: 8600, author_followers: 31000,
    reasoning: 'Extreme claim + 3 concrete numbers.',
  },
  {
    hook_text: 'Design agencies are the next Kodak.\nHere\'s why.',
    raw_text: 'Design agencies are the next Kodak. Here\'s why. - Their unit economics assume human hours. - Their clients now expect hourly turnaround. - Their best people are leaving to build tools. The incumbents saw the disruption. They just can\'t price it.',
    pattern_name: 'The Bold Claim + Evidence',
    source: 'linkedin', source_url: 'https://linkedin.com/posts/demo-54',
    engagement_score: 7400, author_followers: 22000,
    reasoning: 'Analogy + structural evidence.',
  },
  {
    hook_text: 'SEO is not dead.\nBut link-building is.',
    raw_text: 'SEO is not dead. But link-building is. - Google\'s 2024 updates killed 80% of guest-post juice. - Original data drops outrank link farms every time. - Our best-performing post has 0 backlinks and ranks #2. Write the study. Skip the outreach.',
    pattern_name: 'The Bold Claim + Evidence',
    source: 'linkedin', source_url: 'https://linkedin.com/posts/demo-55',
    engagement_score: 6200, author_followers: 19000,
    reasoning: 'Nuanced bold claim + evidence.',
  },
  {
    hook_text: 'Most "AI strategies" are rebranded roadmaps.\nHere\'s the test.',
    raw_text: 'Most "AI strategies" are rebranded roadmaps. Here\'s the test. - Does it change who does the work? - Does it change the unit economics? - Does it change what you sell? If three no\'s, it\'s a slide deck, not a strategy.',
    pattern_name: 'The Bold Claim + Evidence',
    source: 'linkedin', source_url: 'https://linkedin.com/posts/demo-56',
    engagement_score: 5800, author_followers: 22000,
    reasoning: 'Critique + operational test.',
  },
  {
    hook_text: 'Every Amazon seller will use AI image tools by 2026.\nHere\'s the proof.',
    raw_text: 'Every Amazon seller will use AI image tools by 2026. Here\'s the proof. - Amazon\'s own listing editor shipped AI image gen this year. - The top 100 brands in our data set already use it. - Cost per image dropped 98% since 2023. The adoption curve is already bending. Most sellers just haven\'t noticed.',
    pattern_name: 'The Bold Claim + Evidence',
    source: 'linkedin', source_url: 'https://linkedin.com/posts/demo-57',
    engagement_score: 10400, author_followers: 31000,
    reasoning: 'Category prediction + three hard proofs.',
  },
  {
    hook_text: 'Founder-led sales is not a phase.\nIt\'s the permanent advantage.',
    raw_text: 'Founder-led sales is not a phase. It\'s the permanent advantage. - Founders close 3x faster on first calls. - Founders hear objections nobody else will admit. - Founders can reprice mid-call. Hire the AE when the founder runs out of hours, not sooner.',
    pattern_name: 'The Bold Claim + Evidence',
    source: 'linkedin', source_url: 'https://linkedin.com/posts/demo-58',
    engagement_score: 9100, author_followers: 48000,
    reasoning: 'Contrarian prescription + 3 reasons.',
  },
  {
    hook_text: 'LinkedIn beats cold email for B2B in 2025.\nThree data points.',
    raw_text: 'LinkedIn beats cold email for B2B in 2025. Three data points. - Our reply rate on LI DMs: 18%. On email: 2%. - Our ICP lives in the feed. They don\'t read inbox pitches anymore. - One post per week out-pulls 400 cold emails. Post the insight. Let the DM come to you.',
    pattern_name: 'The Bold Claim + Evidence',
    source: 'linkedin', source_url: 'https://linkedin.com/posts/demo-59',
    engagement_score: 8700, author_followers: 22000,
    reasoning: 'Channel claim + side-by-side metrics.',
  },
  {
    hook_text: 'The next billion-dollar e-commerce tool is not a store builder.\nIt\'s an image engine.',
    raw_text: 'The next billion-dollar e-commerce tool is not a store builder. It\'s an image engine. - Images drive 70%+ of conversion on marketplaces. - Image costs are the last uncompressed line in seller P&Ls. - Every new marketplace (TikTok Shop, Temu, Meta Shops) is image-first. We\'re building for exactly that.',
    pattern_name: 'The Bold Claim + Evidence',
    source: 'linkedin', source_url: 'https://linkedin.com/posts/demo-60',
    engagement_score: 12000, author_followers: 48000,
    reasoning: 'Market prediction + three structural proofs (and on-brand).',
  },
];
